"use client"

import { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { addUser, setLoginState } from '@/Redux/UserSlice';
import axios from '@/axios';
import { useRouter } from 'next/navigation';

import { Inter } from 'next/font/google'

import AppBarComponent from '@/components/AppBar/AppBarComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const dispatch = useDispatch();
  const router = useRouter();
  let tokenFromLS;
  if (typeof window !== 'undefined') {
    tokenFromLS = localStorage.getItem('tokenBS');

  }
  
  
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {

    async function fetchData() {
      try {
        setIsLoading(true)

        const response = await axios.post('/getUser', { token: tokenFromLS });

        dispatch(setLoginState(true));
        dispatch(addUser(response.data.user));
        // if (response.data.user.role === 'admin') {
        //   router.push('/admin');
        // } else {
        //   router.push('/dashboard/books');
        // }
        setIsLoading(false)

      } catch (error) {
        console.log(error.response);
        setIsLoading(false)

        router.push('/bib/signin');
      }
    }

    if (tokenFromLS) {
      fetchData();
    } else {
      router.push('/bib/signin');
    }
  }, [dispatch, router, tokenFromLS]);

  
  return (
    <html lang="en">

      <body className={inter.className}>
        {isLoading ? null : <>
          <AppBarComponent />
          {children}</>}

      </body>
    </html>
  )
}
